### ISSUE TITLE
Other model formats

### ISSUE THREAD

**Issue by eziosoft** [stephansturges/OpenLander#2]
Hey! Thanks for you hard work !
Will be other formats other than `.blob` provided ? 
I would love to run this on my local machine for tests without having to buy OAK-D device at this stage.

**Comment by stephansturges** [comment]
Hey Bartosz! Yeah I've been planning to export the models from this repo as ONNX for a while now but other things keep getting in the way… I'll do it next week hopefully :)

*Stephan Sturges /* *🚁* *abuzz.ai ( http://abuzz.ai )* *🛩️*
+32 484 06 19 63
**

**Comment by eziosoft** [comment]
Hi
Any news about ONNX format ?

**Comment by stephansturges** [comment]
Thanks for reminding me, I'll take a look at this tomorrow 👍

**Comment by stephansturges** [comment]
Turns out I can't export the models that are in this repo to ONNX: I only kept the TF representation with a frozen graph and would need to retrain to get back to a model I can export. 
Since I'm changing the model format to something completely new I don't want to retrain with those settings, so this won't be solved for a while.

**Comment by stephansturges** [comment]
Check ou the first ONNX model from here:

https://huggingface.co/spaces/StephanST/OpenLanderONNXonline

you can use the app online and you can also pull the code and model.

Bear in mind this is Gen1 in that format, I'm currently retraining it to match the performance of the embedded system, them I will also train a larger version :)

**Comment by eziosoft** [comment]
thanks a lot. I'll try it asap
